### ISSUE TITLE
node red naming convention

### ISSUE THREAD

**Issue by ukmoose** [ephraim/node-red-contrib-fprint#1]
Any reason you didn't follow the node-red naming convention?

http://nodered.org/docs/creating-nodes/packaging.html

"Node packages that are maintained by the Node-RED project use the prefix node-red-node-. 3rd party nodes should chose a naming scheme that avoids that prefix."

**Comment by ephraim** [comment]
Yeah!
I didn't know anything about that "rule".
Have a good day.

Am 07.11.2015 9:33 nachm. schrieb ukmoose notifications@github.com:Any reason you didn't follow the node-red naming convention?

http://nodered.org/docs/creating-nodes/packaging.html

"Node packages that are maintained by the Node-RED project use the prefix node-red-node-. 3rd party nodes should chose a naming scheme that avoids that prefix."
