### ISSUE TITLE
info for only verify

### ISSUE THREAD

**Issue by marcello49** [ephraim/node-red-contrib-fprint#4]
Hi, 
I installed my usb microsoft reader (usb) U4000 / 4000b / 4500 fingerprint correctly installed and ready for use/running with fprint_demo.
I have problems with node-red and your example: 
enroll-verify inject: enroll-started, enroll-stage-passed for 5 times(stage5/5), enroll-completed with fingerprint: 789c .... and after verify-started, verify-succeeded and after fingerprint: 789c8d9 ..... all right. it works very well.
if I want to start only a check how should I do?
I used google translator, sorry
thank you

**Comment by ephraim** [comment]
You need to save the output of the enroll to e.g. a database.
Afterwards, when you want to verify take the content of the database and verify against that.
No need to do enroll and verify in once. Thats just an example how to use the nodes.
